### ISSUE TITLE
Some other issues

### ISSUE THREAD

**Issue by ricardoalcocer** [ricardoalcocer/jssql#14]
@caspahouzer

Please see this:
https://github.com/ricardoalcocer/jssql/blob/master/app/lib/com.alcoapps.dbhelper.js#L54 ,  This error should be a callback that the user can react to.

Also 
https://github.com/ricardoalcocer/jssql/blob/master/app/lib/com.alcoapps.dbhelper.js#L207 and https://github.com/ricardoalcocer/jssql/blob/master/app/lib/com.alcoapps.dbhelper.js#L268 , this broke after getData was implemented...I'm assuming it's because that by the time getLastInsertedRecordId is called, getData already closed the DB connection.

Lastly, run the app.  I started providing a best test app, but stopped after I found those issues.

Any thoughts?

**Comment by ricardoalcocer** [comment]
Pull this new version...has a couple changes on top of your recent PR.

**Comment by caspahouzer** [comment]
Started working and fixing the issues by closing the db connection manually and not in getData. Also reimplements getLastInsertedId and affected rows on update and delete

**Comment by ricardoalcocer** [comment]
Great, thanks.  I'll hold of the sample app until I get an update.  I appreciate the help.

**Comment by caspahouzer** [comment]
Honor for me. Thanks

**Comment by ricardoalcocer** [comment]
Thank you.  Those changes fixed the last index issue.  I'll continue to work on a better sample app.
